### ISSUE TITLE
Fix canvas autosizing

### ISSUE THREAD

**Issue by BrendanAnnable** [NUbots/NUsight2#6]
Currently when making the browser window small in the localisation window, the canvas does not shrink down to size.

**Comment by JosephusPaye** [comment]
Hi Brendan,

I took a stab at doing it with CSS, using [calc](https://developer.mozilla.org/en/docs/Web/CSS/calc) and [viewport units](https://www.quirksmode.org/css/units-values/viewport.html):

```css
.localisation__canvas {
    /* remove flex-grow */
    /* flex-grow: 1; */

    width: calc(100vw - 147px); /* 147px is the width of the sidebar menu, could use a variable here */
    height: calc(100vh - 60px); /* 60px is the height of the header */
} 
```

Then, to keep the status bar visible:

```css
.localisation__status {
    /* remove bottom */
    /* bottom: 8px; */

    top: calc(100vh - 60px); /* 60px is the height of the header */
}
```

Result (Chrome):

![nusight-canvas-resize](https://cloud.githubusercontent.com/assets/5924865/26021264/962755b8-37cd-11e7-90a1-7da6b67ee857.gif)

_(1MB gif, make take a while to load)_

I can make a pull request if this is good.
